import type { Move } from "./types";

// MVP用の最小限の技データ（威力・分類・タイプ）
export const MOVE_LIST: Move[] = [
  { name: "じしん", power: 100, category: "physical", type: "じめん" },
  { name: "いわなだれ", power: 75, category: "physical", type: "いわ" },
  { name: "ストーンエッジ", power: 100, category: "physical", type: "いわ" },
  { name: "アイアンヘッド", power: 80, category: "physical", type: "はがね" },
  { name: "アイアンテール", power: 100, category: "physical", type: "はがね" },
  { name: "ドラゴンクロー", power: 80, category: "physical", type: "ドラゴン" },
  { name: "げきりん", power: 120, category: "physical", type: "ドラゴン" },
  { name: "インファイト", power: 120, category: "physical", type: "かくとう" },
  { name: "ばかぢから", power: 120, category: "physical", type: "かくとう" },
  { name: "つばめがえし", power: 60, category: "physical", type: "ひこう" },
  { name: "ブレイブバード", power: 120, category: "physical", type: "ひこう" },
  { name: "とんぼがえり", power: 70, category: "physical", type: "むし" },
  { name: "シザークロス", power: 80, category: "physical", type: "むし" },
  { name: "じゃれつく", power: 90, category: "physical", type: "フェアリー" },
  { name: "イカサマ", power: 95, category: "physical", type: "あく" },
  { name: "のしかかり", power: 85, category: "physical", type: "ノーマル" },
  { name: "ギガインパクト", power: 150, category: "physical", type: "ノーマル" },
  { name: "かえんほうしゃ", power: 90, category: "special", type: "ほのお" },
  { name: "なみのり", power: 90, category: "special", type: "みず" },
  { name: "10まんボルト", power: 90, category: "special", type: "でんき" },
  { name: "10まんばりき", power: 90, category: "physical", type: "でんき" },
  { name: "リーフストーム", power: 130, category: "special", type: "くさ" },
  { name: "サイコキネシス", power: 90, category: "special", type: "エスパー" },
  { name: "シャドーボール", power: 80, category: "special", type: "ゴースト" },
  { name: "ヘドロばくだん", power: 90, category: "special", type: "どく" },
  { name: "むしのさざめき", power: 90, category: "special", type: "むし" },
  { name: "れいとうビーム", power: 90, category: "special", type: "こおり" },
  { name: "フリーズドライ", power: 70, category: "special", type: "こおり" },
  { name: "ムーンフォース", power: 95, category: "special", type: "フェアリー" },
  { name: "はどうだん", power: 80, category: "special", type: "かくとう" },
  { name: "パワージェム", power: 80, category: "special", type: "いわ" },
  { name: "はかいこうせん", power: 150, category: "special", type: "ノーマル" },
];
