import type { Move } from "./types";

/**
 * ポケモンチャンピオンズの技マスタ（威力・分類・タイプ）
 * 出典: https://app.gamepedia.jp/pokemon-champions/moves
 * 採用率: https://champs.pokedb.tokyo/
 *
 * 体重依存（くさむすび）は固定威力がないため、計算用に代表値 80 を置く。
 * 連続技は1ヒット分の威力。
 */
export const MOVE_LIST: Move[] = [
  // 物理
  { name: "じしん", power: 100, category: "physical", type: "じめん" },
  { name: "スケイルショット(未対応)", power: 25, category: "physical", type: "ドラゴン" },
  { name: "げきりん", power: 120, category: "physical", type: "ドラゴン" },
  { name: "がんせきふうじ", power: 60, category: "physical", type: "いわ" },
  { name: "ドラゴンテール", power: 60, category: "physical", type: "ドラゴン" },
  { name: "いわなだれ", power: 75, category: "physical", type: "いわ" },
  { name: "どくづき", power: 80, category: "physical", type: "どく" },
  { name: "じゃれつく", power: 90, category: "physical", type: "フェアリー" },
  { name: "かげうち", power: 40, category: "physical", type: "ゴースト" },
  { name: "シャドークロー", power: 70, category: "physical", type: "ゴースト" },
  { name: "ウッドハンマー", power: 120, category: "physical", type: "くさ" },
  { name: "ドレインパンチ", power: 75, category: "physical", type: "かくとう" },
  { name: "こおりのキバ", power: 65, category: "physical", type: "こおり" },
  { name: "トリックフラワー", power: 70, category: "physical", type: "くさ" },
  { name: "トリプルアクセル(未対応)", power: 20, category: "physical", type: "こおり" },
  { name: "とんぼがえり", power: 70, category: "physical", type: "むし" },
  { name: "はたきおとす", power: 65, category: "physical", type: "あく" },
  { name: "ふいうち", power: 70, category: "physical", type: "あく" },
  { name: "かみなりパンチ", power: 75, category: "physical", type: "でんき" },
  { name: "イカサマ", power: 95, category: "physical", type: "あく" },
  { name: "サイコファング", power: 85, category: "physical", type: "エスパー" },
  { name: "バレットパンチ", power: 40, category: "physical", type: "はがね" },
  { name: "れいとうパンチ", power: 75, category: "physical", type: "こおり" },
  { name: "ボディプレス", power: 80, category: "physical", type: "かくとう" },
  { name: "アームハンマー", power: 100, category: "physical", type: "かくとう" },
  { name: "アイアンヘッド", power: 80, category: "physical", type: "はがね" },
  { name: "アクアジェット", power: 40, category: "physical", type: "みず" },
  { name: "クイックターン", power: 60, category: "physical", type: "みず" },
  { name: "たきのぼり", power: 80, category: "physical", type: "みず" },
  { name: "パワーウィップ", power: 120, category: "physical", type: "くさ" },
  { name: "かみくだく", power: 80, category: "physical", type: "あく" },
  { name: "ゆきなだれ", power: 60, category: "physical", type: "こおり" },
  { name: "やけっぱち", power: 75, category: "physical", type: "ほのお" },
  { name: "アクアテール", power: 90, category: "physical", type: "みず" },
  { name: "しんそく", power: 80, category: "physical", type: "ノーマル" },
  { name: "フレアドライブ", power: 120, category: "physical", type: "ほのお" },
  { name: "ニトロチャージ", power: 50, category: "physical", type: "ほのお" },
  { name: "ドラゴンクロー", power: 80, category: "physical", type: "ドラゴン" },
  { name: "インファイト", power: 120, category: "physical", type: "かくとう" },
  { name: "とびひざげり", power: 130, category: "physical", type: "かくとう" },
  { name: "ブレイズキック", power: 85, category: "physical", type: "ほのお" },
  { name: "ブレイブバード", power: 120, category: "physical", type: "ひこう" },
  { name: "つけあがる", power: 20, category: "physical", type: "あく" },
  { name: "キラースピン", power: 30, category: "physical", type: "どく" },
  { name: "こおりのつぶて", power: 40, category: "physical", type: "こおり" },
  { name: "おはかまいり", power: 50, category: "physical", type: "ゴースト" },
  { name: "ウェーブタックル", power: 120, category: "physical", type: "みず" },
  { name: "もろはのずつき", power: 150, category: "physical", type: "いわ" },
  { name: "アクアブレイク", power: 85, category: "physical", type: "みず" },
  { name: "ダブルウイング", power: 40, category: "physical", type: "ひこう" },
  { name: "むしくい", power: 60, category: "physical", type: "むし" },
  { name: "かわらわり", power: 75, category: "physical", type: "かくとう" },
  { name: "ねこだまし", power: 40, category: "physical", type: "ノーマル" },
  { name: "くさわけ", power: 50, category: "physical", type: "くさ" },
  { name: "アイススピナー", power: 80, category: "physical", type: "こおり" },
  { name: "しねんのずつき", power: 80, category: "physical", type: "エスパー" },
  { name: "サイコカッター", power: 70, category: "physical", type: "エスパー" },
  { name: "こうそくスピン", power: 50, category: "physical", type: "ノーマル" },
  { name: "ポルターガイスト", power: 110, category: "physical", type: "ゴースト" },
  { name: "せいなるつるぎ", power: 90, category: "physical", type: "かくとう" },
  { name: "ひけん・ちえなみ", power: 65, category: "physical", type: "あく" },
  { name: "シェルブレード", power: 75, category: "physical", type: "みず" },
  { name: "アクアカッター", power: 70, category: "physical", type: "みず" },
  { name: "すてみタックル", power: 120, category: "physical", type: "ノーマル" },
  { name: "ドゲザン", power: 85, category: "physical", type: "あく" },
  { name: "ドラゴンアロー", power: 50, category: "physical", type: "ドラゴン" },
  { name: "ゴーストダイブ", power: 90, category: "physical", type: "ゴースト" },
  { name: "コメットパンチ", power: 90, category: "physical", type: "はがね" },
  { name: "ソウルクラッシュ", power: 75, category: "physical", type: "フェアリー" },
  { name: "ほのおのキバ", power: 65, category: "physical", type: "ほのお" },
  { name: "マッハパンチ", power: 40, category: "physical", type: "かくとう" },
  { name: "メガトンキック", power: 120, category: "physical", type: "ノーマル" },
  { name: "でんこうせっか", power: 40, category: "physical", type: "ノーマル" },
  { name: "むねんのつるぎ", power: 90, category: "physical", type: "ほのお" },
  { name: "ストーンエッジ", power: 100, category: "physical", type: "いわ" },
  { name: "ロックブラスト", power: 25, category: "physical", type: "いわ" },
  { name: "しっぺがえし", power: 50, category: "physical", type: "あく" },
  { name: "フェイタルクロー", power: 80, category: "physical", type: "どく" },
  { name: "じごくづき", power: 80, category: "physical", type: "あく" },
  { name: "アクロバット", power: 55, category: "physical", type: "ひこう" },
  { name: "だいばくはつ", power: 250, category: "physical", type: "ノーマル" },
  { name: "うちおとす", power: 50, category: "physical", type: "いわ" },
  { name: "のしかかり", power: 85, category: "physical", type: "ノーマル" },
  { name: "じばく", power: 200, category: "physical", type: "ノーマル" },
  { name: "つららばり", power: 25, category: "physical", type: "こおり" },
  { name: "つららおとし", power: 85, category: "physical", type: "こおり" },
  { name: "ネズミざん", power: 20, category: "physical", type: "ノーマル" },
  { name: "かみつく", power: 60, category: "physical", type: "あく" },
  { name: "タネマシンガン", power: 25, category: "physical", type: "くさ" },
  { name: "ふんどのこぶし", power: 50, category: "physical", type: "ゴースト" },
  { name: "きゅうけつ", power: 80, category: "physical", type: "むし" },
  { name: "ダストシュート", power: 120, category: "physical", type: "どく" },
  { name: "とびかかる", power: 80, category: "physical", type: "むし" },
  { name: "とびつく", power: 50, category: "physical", type: "むし" },
  { name: "ばかぢから", power: 120, category: "physical", type: "かくとう" },
  { name: "ヘビーボンバー(未対応)", power: 80, category: "physical", type: "はがね" },
  // 特殊
  { name: "ラスターカノン", power: 80, category: "special", type: "はがね" },
  { name: "りゅうせいぐん", power: 130, category: "special", type: "ドラゴン" },
  { name: "10まんボルト", power: 90, category: "special", type: "でんき" },
  { name: "あくのはどう", power: 80, category: "special", type: "あく" },
  { name: "はどうだん", power: 80, category: "special", type: "かくとう" },
  { name: "エレクトロビーム", power: 130, category: "special", type: "でんき" },
  { name: "ムーンフォース", power: 95, category: "special", type: "フェアリー" },
  { name: "うたかたのアリア", power: 90, category: "special", type: "みず" },
  { name: "なみのり", power: 90, category: "special", type: "みず" },
  { name: "れいとうビーム", power: 90, category: "special", type: "こおり" },
  { name: "エナジーボール", power: 90, category: "special", type: "くさ" },
  { name: "かえんほうしゃ", power: 90, category: "special", type: "ほのお" },
  { name: "マジカルシャイン", power: 80, category: "special", type: "フェアリー" },
  { name: "サイコキネシス", power: 90, category: "special", type: "エスパー" },
  { name: "サイコショック", power: 80, category: "special", type: "エスパー" },
  { name: "マジカルフレイム", power: 75, category: "special", type: "ほのお" },
  { name: "エアスラッシュ", power: 75, category: "special", type: "ひこう" },
  { name: "ソーラービーム", power: 120, category: "special", type: "くさ" },
  { name: "オーバーヒート", power: 130, category: "special", type: "ほのお" },
  { name: "ウェザーボール", power: 50, category: "special", type: "ノーマル" },
  { name: "だいもんじ", power: 110, category: "special", type: "ほのお" },
  { name: "だいちのちから", power: 90, category: "special", type: "じめん" },
  { name: "きあいだま", power: 120, category: "special", type: "かくとう" },
  { name: "ヘドロウェーブ", power: 95, category: "special", type: "どく" },
  { name: "みずしゅりけん", power: 15, category: "special", type: "みず" },
  { name: "ハイドロポンプ", power: 110, category: "special", type: "みず" },
  { name: "マッドショット", power: 55, category: "special", type: "じめん" },
  { name: "ボルトチェンジ", power: 70, category: "special", type: "でんき" },
  { name: "ほうでん", power: 80, category: "special", type: "でんき" },
  { name: "パワージェム", power: 80, category: "special", type: "いわ" },
  { name: "ヘドロばくだん", power: 90, category: "special", type: "どく" },
  { name: "フリーズドライ", power: 70, category: "special", type: "こおり" },
  { name: "ふぶき", power: 110, category: "special", type: "こおり" },
  { name: "シャドーボール", power: 80, category: "special", type: "ゴースト" },
  { name: "こごえるかぜ", power: 55, category: "special", type: "こおり" },
  { name: "たたりめ", power: 65, category: "special", type: "ゴースト" },
  { name: "でんじほう", power: 120, category: "special", type: "でんき" },
  { name: "みわくのボイス", power: 80, category: "special", type: "フェアリー" },
  { name: "パラボラチャージ", power: 65, category: "special", type: "でんき" },
  { name: "アシッドボム", power: 40, category: "special", type: "どく" },
  { name: "フレアソング", power: 80, category: "special", type: "ほのお" },
  { name: "もえつきる", power: 130, category: "special", type: "ほのお" },
  { name: "ゴールドラッシュ", power: 120, category: "special", type: "はがね" },
  { name: "しんくうは", power: 40, category: "special", type: "かくとう" },
  { name: "バークアウト", power: 55, category: "special", type: "あく" },
  { name: "げんしのちから", power: 60, category: "special", type: "いわ" },
  { name: "ほのおのまい", power: 80, category: "special", type: "ほのお" },
  { name: "ギガドレイン", power: 75, category: "special", type: "くさ" },
  { name: "むしのさざめき", power: 90, category: "special", type: "むし" },
  { name: "ハイパーボイス", power: 90, category: "special", type: "ノーマル" },
  { name: "はかいこうせん", power: 150, category: "special", type: "ノーマル" },
  { name: "ぼうふう", power: 110, category: "special", type: "ひこう" },
  { name: "まとわりつく", power: 20, category: "special", type: "むし" },
  { name: "ひやみず", power: 50, category: "special", type: "みず" },
  { name: "アシストパワー", power: 20, category: "special", type: "エスパー" },
  { name: "チャージビーム", power: 50, category: "special", type: "でんき" },
  { name: "みずのはどう", power: 60, category: "special", type: "みず" },
  { name: "りゅうのはどう", power: 85, category: "special", type: "ドラゴン" },
  { name: "しおふき", power: 150, category: "special", type: "みず" },
  { name: "ドレインキッス", power: 50, category: "special", type: "フェアリー" },
  { name: "はめつのひかり", power: 140, category: "special", type: "フェアリー" },
  { name: "ルミナコリジョン", power: 80, category: "special", type: "エスパー" },
  { name: "リーフストーム", power: 130, category: "special", type: "くさ" },
  { name: "しっとのほのお", power: 70, category: "special", type: "ほのお" },
  { name: "ほのおのうず", power: 35, category: "special", type: "ほのお" },
  { name: "ねっとう", power: 80, category: "special", type: "みず" },
  { name: "こおりのいぶき", power: 60, category: "special", type: "こおり" },
  { name: "うらみつらみ", power: 75, category: "special", type: "ゴースト" },
  { name: "シャカシャカほう", power: 80, category: "special", type: "くさ" },
  // 体重依存 / 連続技など計算未対応
  { name: "くさむすび(未対応)", power: 80, category: "special", type: "くさ" },
];

export const MOVE_BY_NAME: Record<string, Move> = Object.fromEntries(
  MOVE_LIST.map((m) => [m.name, m]),
);

export function findMoveByName(name: string): Move | undefined {
  return MOVE_BY_NAME[name];
}
